# Generated by Django 5.2.16 on 2026-08-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password_hash',
            field=models.CharField(blank=True, help_text='Hashed password for student login', max_length=128, null=True),
        ),
    ]
