# Generated by Django 5.2.16 on 2026-08-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('lectures', '0001_initial'),
        ('qr_codes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='lectures.lecture'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='qr_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attendance_records', to='qr_codes.qrcodesession'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attendance_records', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'lecture')},
        ),
    ]
