# Generated by Django 5.2.16 on 2026-08-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultysubjectassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_assignments', to='subjects.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='facultysubjectassignment',
            unique_together={('faculty', 'subject', 'section', 'academic_year')},
        ),
    ]
