# Generated by Django 5.2.16 on 2026-08-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lectures', to='subjects.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('faculty', 'lecture_date', 'lecture_number')},
        ),
    ]
